name: CI-CD-Pipeline-to-AWS-ElasticBeanstalk
env:
  EB_PACKAGE_S3_BUCKET_NAME : "sdi-it-flask-app-packages"
  EB_APPLICATION_NAME       : "MyFlask"
  EB_ENVIROMENT_NAME        : "MyFlask-env"
  DEPLOY_PACKAGE_NAME       : "flask_app_${{ github.sha }}.zip"
  AWS_REGION_NAME           : "eu-central-1"

on:
  push:
    branches: 
     - master

jobs:
  my_ci_part:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone our repo
        uses: actions/checkout@v1

      - name: Create ZIP deployment package
        run: zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*
        
      - name: Configure my AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id        : ${{ secrets.MY_AWS_ACCESS_KEY }}
          aws-secret-access-key    : ${{ secrets.MY_AWS_SECRET_KEY }}
          aws-region               : ${{ env.AWS_REGION_NAME }}


      - name: Copy deployment package to S3 bucket
        run: aws s3 cp ${{ env.DEPLOY_PACKAGE_NAME }} s3://${{ env.EB_PACKAGE_S3_BUCKET_NAME }}/
      
      - name: Print Happy Message for CI finish
        run: echo "CI Pipeline part finished succesfully!"

  my_cd_part:
    runs-on: ubuntu-latest
    needs: [my_ci_part]

    steps:
      - name: Configure my AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id        : ${{ secrets.MY_AWS_ACCESS_KEY }}
          aws-secret-access-key    : ${{ secrets.MY_AWS_SECRET_KEY }}
          aws-region               : ${{ env.AWS_REGION_NAME }}
          
      - name: Create new ElasticBeanstalk Application
        run :
          aws elasticBeanstalk create-application-version \
          --application name ${{ env.EB_APPLICATION_NAME }} \
          --source-boundle S3Bucket="${{ env.EB_PACKAGE_S3_BUCKET_NAME }}", S3Key=""${{ env.DEPLOY_PACKAGE_NAME }}" \
          --version-label "Ver-${{ github.sha }}" \
          --description "CommitSHA-${{ github.sha }}"
          
      - name: Deploy new Elasticbeanstalk Application Version
        run: aws elasticbeanstalk update-enviroment --enviroment-name ${{ env.EB_ENVIROMENT_NAME }} --version-label "Ver-${{ github.sha }}"         
          
      - name: Print Happy Message for CD finish
        run: echo "CD Pipeline part finished succesfully!"
                  
